name: Pipeline CI/CD DevSecOps Juice Shop

on:
  push:
    branches:
      - main

jobs:
  setup-and-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Juice Shop repo
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build Docker image
        run: docker build -t juice-shop:latest .
      
      - name: SCA - npm audit
        run: npm audit --audit-level=high || true

      - name: SAST - semgrep scan
        run: |
          pip install semgrep
          semgrep scan --config auto

      - name: Secrets Scan - gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        with:
          config-path: ""
        continue-on-error: true

      - name: Run Juice Shop container
        run: docker run -d -p 3000:3000 juice-shop:latest && sleep 10

      - name: DAST - OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
        continue-on-error: true
