name: DevSecOps Juice Shop CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write  

jobs:
  devsecops:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged

    steps:
      - name: Checkout repo (Twoj kod)
        uses: actions/checkout@v3

      - name: Klonowanie Juice Shop
        run: git clone https://github.com/juice-shop/juice-shop.git

      - name: Instalacja zaleznosci
        working-directory: juice-shop
        run: npm install

      - name: Budowanie Juice Shop (Docker)
        working-directory: juice-shop
        run: docker build -t juice-shop-app .

      - name: SCA - npm audit
        working-directory: juice-shop
        run: npm audit --audit-level=high || true

      - name: SAST - Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          working-directory: juice-shop

      - name: Sekrety - GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect -s juice-shop

      - name: Uruchomienie Juice Shop
        run: docker run -d -p 3000:3000 --name juice-shop juice-shop-app

      - name: Poczekaj az aplikacja wystartuje
        run: sleep 10

      - name: DAST - OWASP ZAP
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-t 300 -a -r zap_report.html -I'
