name: DevSecOps Juice Shop CI/CD

permissions:
  contents: read
  pull-requests: write
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  devsecops:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      DOCKER_TLS_CERTDIR: ""  # wyłącz TLS w DinD, ułatwia działanie
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Juice Shop Docker image
        run: docker build -t juice-shop:latest .

      - name: Run Juice Shop container
        run: |
          docker run -d --rm -p 3000:3000 --name juice-shop juice-shop:latest

      - name: Wait for Juice Shop to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Waiting for Juice Shop..."
            sleep 5
          done

      # --- SCA: Security Check of Dependencies ---
      - name: Run OWASP Dependency-Check (Java example)
        uses: dependency-check/github-action@v6
        with:
          scan: './'  # jeśli npm albo pip - zmień konfigurację pod siebie
          format: 'ALL'
        continue-on-error: true

      # --- SAST: Semgrep static analysis ---
      - name: Run Semgrep SAST scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'auto'
        continue-on-error: true

      # --- Secrets scan ---
      - name: GitLeaks secret scan
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: true

      # --- DAST: OWASP ZAP dynamic scan ---
      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-t 5 -a -r zap_report.html -I'

      - name: Upload OWASP ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html

      # Cleanup
      - name: Stop Juice Shop container
        run: docker stop juice-shop || true
